version: "3.9"

services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: batumi
      POSTGRES_PASSWORD: batumi
      POSTGRES_DB: batumi_lunch
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
  api:
    build:
      context: ..
      dockerfile: deploy/Dockerfile.api
    env_file:
      - ../.env.sample
    environment:
      DATABASE_URL: postgresql+asyncpg://batumi:batumi@db:5432/batumi_lunch
      REDIS_URL: redis://redis:6379/0
    depends_on:
      - db
      - redis
    ports:
      - "8000:8000"
  web:
    build:
      context: ../frontend
      dockerfile: ../deploy/Dockerfile.web
    env_file:
      - ../.env.sample
    depends_on:
      - api
    ports:
      - "3000:3000"

volumes:
  postgres-data:
